package: download_area
version: '0.1'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/download_area


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"



page:
    title: translate:download_area_title
    prio: 100
    icon: rex-icon fa-gear

pages:
    download_area:
        title: translate:download_area_title

        block: system
        prio: 15
        icon: rex-icon fa-download
        perm: download_area[]
        subpages:
            download:
                title: translate:download_area_download
                icon: rex-icon fa-download
                perm: download_area[]
            settings:
                title: translate:download_area_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:download_area_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: download_area[docs]

default_config:
    field: 'Test'
